'use client';

import { useState, useEffect, useRef, useCallback, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Download, FileText, Loader2, AlertCircle, BarChart3, Code, CheckCircle, Activity, ArrowLeft, Search, Sparkles, Globe, LayoutDashboard, ArrowRight, PenTool, TrendingUp } from 'lucide-react';
import { toast } from 'sonner';

interface ReportData {
  htmlContent: string;
  customerName: string;
  reportType: string;
  generatedAt: string;
}

import './report.css';

function AEOReportContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const hasAutoGenerated = useRef(false);
  const [customerName, setCustomerName] = useState('');
  const [url, setUrl] = useState('');
  const [competitors, setCompetitors] = useState<any[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFetchingReport, setIsFetchingReport] = useState(false);
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [generationSuccess, setGenerationSuccess] = useState(false);
  const [reportId, setReportId] = useState<string | null>(null);
  const [loadingStep, setLoadingStep] = useState(0);

  const brandId = searchParams.get('brandId');

  // Loading steps animation
  useEffect(() => {
    if (isGenerating || (isFetchingReport && !reportData)) {
      const interval = setInterval(() => {
        setLoadingStep((prev) => (prev + 1) % 4);
      }, 2000);
      return () => clearInterval(interval);
    }
  }, [isGenerating, isFetchingReport, reportData]);

  const generateReport = useCallback(async (nameOverride?: string, urlOverride?: string) => {
    const nameToUse = typeof nameOverride === 'string' ? nameOverride : customerName;
    const urlToUse = typeof urlOverride === 'string' ? urlOverride : url;

    if (!nameToUse.trim()) {
      toast.error('Please enter a customer name');
      return;
    }

    if (!urlToUse.trim()) {
      toast.error('Please enter a website URL');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGenerationSuccess(false);
    setReportData(null);
    setReportId(null);

    try {
      const response = await fetch('/api/aeo-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerName: nameToUse.trim(),
          url: urlToUse.trim(),
          reportType: 'combined',
          competitors,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate report');
      }

      setReportId(data.reportId);
      setGenerationSuccess(true);
      toast.success('Report generation started!');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setIsGenerating(false);
    }
  }, [customerName, url]);

  useEffect(() => {
    let intervalId: NodeJS.Timeout;
    let timeoutId: NodeJS.Timeout;
    let attempts = 0;
    const POLL_INTERVAL = 5000; // Poll every 5 seconds for faster feedback
    const MAX_ATTEMPTS = 180; // ~15 minutes

    const fetchFullReport = async () => {
      try {
        const res = await fetch(`/api/aeo-reports/${reportId}/view`, {
          headers: { 'Cache-Control': 'no-cache' },
        });
        if (res.status === 200) {
          const html = await res.text();
          setReportData({
            htmlContent: html,
            customerName: customerName || searchParams.get('customerName') || 'Brand', 
            reportType: 'combined',
            generatedAt: new Date().toISOString()
          });
          setGenerationSuccess(false);
          setIsFetchingReport(false);
          toast.success('Report ready!');
        } else {
          setError(`Failed to fetch report content (Status: ${res.status})`);
        }
      } catch (e) {
        setError('Error downloading report content');
      }
    };

    const startPolling = () => {
      pollCheck();
      intervalId = setInterval(pollCheck, POLL_INTERVAL);
    };

    const pollCheck = async () => {
      attempts++;
      try {
        const res = await fetch(`/api/aeo-reports/${reportId}/view?check=true`, {
          headers: { 'Cache-Control': 'no-cache' },
        });

        if (res.status === 200) {
          const data = await res.json();
          if (data.ready) {
            clearInterval(intervalId);
            fetchFullReport();
          } else {
            if (attempts >= MAX_ATTEMPTS) {
              clearInterval(intervalId);
              setIsFetchingReport(false);
              setGenerationSuccess(false);
              setError('Report generation timed out. Please try again.');
            }
          }
        } else if (res.status === 404) {
           clearInterval(intervalId);
           setIsFetchingReport(false);
           setGenerationSuccess(false);
           setError('Report not found.');
        }
      } catch (e) {
        console.error('Polling check failed', e);
      }
    };

    if (reportId && !reportData) {
      setIsFetchingReport(true);
      
      if (generationSuccess) {
         timeoutId = setTimeout(startPolling, 30000); 
      } else {
         startPolling();
      }
    }

    return () => {
      if (intervalId) clearInterval(intervalId);
      if (timeoutId) clearTimeout(timeoutId);
    };
  }, [reportId, reportData, customerName, generationSuccess]);

  useEffect(() => {
    const paramName = searchParams.get('customerName');
    const paramUrl = searchParams.get('url');
    const paramCompetitors = searchParams.get('competitors');
    const auto = searchParams.get('auto');
    const paramReportId = searchParams.get('reportId');

    if (paramReportId && !reportData && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      setReportId(paramReportId);
      return;
    }

    if (paramName) setCustomerName(paramName);
    if (paramUrl) setUrl(paramUrl);
    if (paramCompetitors) {
      try {
        const parsed = JSON.parse(paramCompetitors);
        if (Array.isArray(parsed)) setCompetitors(parsed);
      } catch (e) {
        // ignore invalid json
      }
    }

    if (auto === 'true' && paramName && paramUrl && !hasAutoGenerated.current && !reportData) {
      hasAutoGenerated.current = true;
      generateReport(paramName, paramUrl);
    } else if (!auto || !paramName || !paramUrl) {
      hasAutoGenerated.current = false;
    }
  }, [searchParams, generateReport, reportData]);

  const downloadPDF = async () => {
    if (!reportData) return;
    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error('Please allow popups to download PDF');
        return;
      }
      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>AEO Report - ${reportData.customerName}</title>
          <style>
            @media print {
              body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
              .no-print { display: none !important; }
              .page-break { page-break-before: always; }
              table { page-break-inside: avoid; }
              .card { page-break-inside: avoid; margin-bottom: 20px; }
            }
            body { font-family: 'Inter', sans-serif; line-height: 1.6; color: #1e293b; }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }
            .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <div className="header">
            <h1 style="color: #0f172a; font-size: 24px; margin-bottom: 8px;">AEO Intelligence Report</h1>
            <p style="color: #64748b; margin: 0;">Prepared for <strong>${reportData.customerName}</strong> | ${new Date(reportData.generatedAt).toLocaleDateString()}</p>
          </div>
          ${reportData.htmlContent}
          <div class="footer">
            <p>Generated by AEO Intelligence Platform • ${new Date().getFullYear()}</p>
          </div>
        </body>
        </html>
      `;
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
      };
    } catch (err) {
      toast.error('Failed to generate PDF');
    }
  };

  const loadingSteps = [
    { text: "Analyzing brand presence...", icon: Search },
    { text: "Evaluating schema & technical structure...", icon: Code },
    { text: "Measuring sentiment & share of voice...", icon: Activity },
    { text: "Compiling AEO optimization strategy...", icon: FileText },
  ];

  // If a report is loaded, show the View Mode (Success State)
  if (reportData) {
    return (
      <div className="min-h-screen bg-slate-50/50 relative overflow-hidden bg-grid-zinc-100">
        {/* Background Decorative Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <div className="absolute -top-24 -left-24 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-blob" />
            <div className="absolute top-1/2 right-0 w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-3xl animate-blob animation-delay-2000" />
        </div>

        {brandId ? (
            <div className="absolute top-4 left-4 sm:left-6 lg:left-8 z-50">
                <Link 
                href={`/brand-profiles/${brandId}`}
                className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 transition-all bg-white/80 backdrop-blur-md px-4 py-2 rounded-full border border-slate-200/60 hover:bg-white hover:border-slate-300 hover:shadow-md hover:-translate-y-0.5"
                >
                <ArrowLeft className="h-4 w-4" />
                Back to Profile
                </Link>
            </div>
        ) : (
            <div className="absolute top-4 left-4 sm:left-6 lg:left-8 z-50">
                <button 
                onClick={() => setReportData(null)}
                className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 transition-all bg-white/80 backdrop-blur-md px-4 py-2 rounded-full border border-slate-200/60 hover:bg-white hover:border-slate-300 hover:shadow-md hover:-translate-y-0.5"
                >
                <ArrowLeft className="h-4 w-4" />
                Back
                </button>
            </div>
        )}

        <div className="relative z-10 container mx-auto py-12 px-4 max-w-6xl">
            {/* Back Button Removed from here */}
            
            <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start mb-12 mt-8">
                
                {/* Left Column: Report Status & Actions */}
                <div className="md:col-span-7 space-y-6 animate-fade-in-up">
                    <Card className="border-0 shadow-2xl bg-white/80 backdrop-blur-xl overflow-hidden ring-1 ring-slate-200/50 h-full flex flex-col">
                        <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-blue-600 via-indigo-500 to-purple-500" />
                        
                        <CardHeader className="p-8 pb-4">
                            <div className="flex items-start justify-between">
                                <div>
                                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-50 border border-green-100 text-green-700 text-xs font-medium mb-4 animate-pulse">
                                        <span className="relative flex h-2 w-2">
                                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                                          <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
                                        </span>
                                        Analysis Complete
                                    </div>
                                    <CardTitle className="text-3xl font-bold text-slate-900 tracking-tight mb-2">
                                        {reportData.customerName}
                                    </CardTitle>
                                    <CardDescription className="text-slate-500 text-base">
                                        AEO Intelligence Audit • {new Date(reportData.generatedAt).toLocaleDateString()}
                                    </CardDescription>
                                </div>
                                {/* Decorative Icon */}
                                <div className="hidden sm:flex h-14 w-14 bg-blue-50 rounded-2xl items-center justify-center text-blue-600 shadow-inner border border-blue-100">
                                    <FileText className="h-7 w-7" />
                                </div>
                            </div>
                        </CardHeader>

                        <CardContent className="p-8 pt-2 space-y-8 flex-1 flex flex-col justify-between">
                             <p className="text-slate-600 leading-relaxed text-lg">
                                This report evaluates how effectively your data is structured for Large Language Models. It checks your structured data, content clarity, and machine-readability to ensure optimal performance in AI-driven search.
                             </p>
                             
                             {/* Action Buttons */}
                             <div className="flex flex-col sm:flex-row gap-4">
                                <Button 
                                    onClick={() => {
                                        const newWindow = window.open('', '_blank');
                                        if (newWindow) {
                                            newWindow.document.write(reportData.htmlContent);
                                            newWindow.document.close();
                                        }
                                    }}
                                    className="flex-1 h-14 text-base font-semibold bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-200/50 rounded-xl transition-all hover:-translate-y-0.5 hover:shadow-blue-300/50"
                                >
                                    <Sparkles className="mr-2 h-5 w-5" />
                                    View Full Report
                                </Button>
                                
                                <Button 
                                    onClick={downloadPDF}
                                    variant="outline"
                                    className="flex-1 h-14 text-base font-medium border-slate-200 hover:bg-slate-50 text-slate-700 rounded-xl transition-colors"
                                >
                                    <Download className="mr-2 h-5 w-5" />
                                    Download PDF
                                </Button>
                             </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Right Column: Highlights */}
                <div className="md:col-span-5 space-y-6 animate-fade-in-up animation-delay-200">
                    <div className="bg-white rounded-2xl shadow-lg border border-slate-100 p-6 h-full">
                        <h4 className="font-semibold text-slate-900 mb-6 flex items-center gap-2">
                            <Activity className="h-5 w-5 text-purple-500" />
                            Included in this Report
                        </h4>
                        <div className="space-y-4">
                            {[
                                { 
                                    icon: BarChart3, 
                                    title: "Optimization Score", 
                                    desc: "Indicates the potential improvement your website can achieve",
                                    containerHover: "group-hover:border-blue-200 group-hover:text-blue-600",
                                    iconHover: "group-hover:text-blue-600"
                                },
                                { 
                                    icon: Code, 
                                    title: "Schema Validation", 
                                    desc: "Technical Structured Data Check",
                                    containerHover: "group-hover:border-indigo-200 group-hover:text-indigo-600",
                                    iconHover: "group-hover:text-indigo-600"
                                },
                                { 
                                    icon: CheckCircle, 
                                    title: "Strategic Roadmap", 
                                    desc: "Actionable Growth Opportunities",
                                    containerHover: "group-hover:border-emerald-200 group-hover:text-emerald-600",
                                    iconHover: "group-hover:text-emerald-600"
                                }
                            ].map((item, i) => (
                                <div key={i} className="flex gap-4 p-4 rounded-xl bg-slate-50/50 border border-slate-100 transition-all hover:bg-white hover:shadow-md hover:border-slate-200 group hover:-translate-y-0.5 cursor-default">
                                    <div className={`mt-1 p-2.5 bg-white rounded-lg border border-slate-100 shadow-sm ${item.containerHover} transition-colors`}>
                                        <item.icon className={`h-5 w-5 text-slate-400 ${item.iconHover} transition-colors`} />
                                    </div>
                                    <div>
                                        <div className="text-sm font-bold text-slate-900">{item.title}</div>
                                        <div className="text-xs text-slate-500 mt-1">{item.desc}</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* Recommended Actions Section */}
            <div className="animate-fade-in-up animation-delay-400">
                <h3 className="text-lg font-semibold text-slate-900 mb-6 flex items-center gap-2">
                    Recommended Next Steps
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <Link href={`/blog-writer?brandId=${brandId || ''}`} className="block group">
                        <Card className="h-full border border-slate-200 hover:border-emerald-300 hover:shadow-xl hover:shadow-emerald-100/50 transition-all duration-300 hover:-translate-y-1 bg-white">
                            <CardContent className="p-6 flex flex-col h-full">
                                <div className="w-12 h-12 bg-emerald-50 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                                    <PenTool className="h-6 w-6 text-emerald-600" />
                                </div>
                                <h4 className="font-semibold text-slate-900 mb-2">Create Content</h4>
                                <p className="text-sm text-slate-500 flex-1">
                                    Use IntelliWrite to generate optimized blog posts based on these findings.
                                </p>
                                <div className="mt-4 flex items-center text-emerald-600 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity transform translate-x-[-10px] group-hover:translate-x-0">
                                    Launch Writer <ArrowRight className="ml-1 h-4 w-4" />
                                </div>
                            </CardContent>
                        </Card>
                    </Link>

                    <Link href={`/brand-monitor?brandId=${brandId || ''}&view=new&url=${encodeURIComponent(url)}`} className="block group">
                        <Card className="h-full border border-slate-200 hover:border-blue-300 hover:shadow-xl hover:shadow-blue-100/50 transition-all duration-300 hover:-translate-y-1 bg-white">
                            <CardContent className="p-6 flex flex-col h-full">
                                <div className="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                                    <TrendingUp className="h-6 w-6 text-blue-600" />
                                </div>
                                <h4 className="font-semibold text-slate-900 mb-2">Monitor Rankings</h4>
                                <p className="text-sm text-slate-500 flex-1">
                                    Set up ongoing tracking to monitor your brand's visibility over time.
                                </p>
                                <div className="mt-4 flex items-center text-blue-600 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity transform translate-x-[-10px] group-hover:translate-x-0">
                                    Go to Monitor <ArrowRight className="ml-1 h-4 w-4" />
                                </div>
                            </CardContent>
                        </Card>
                    </Link>

                    <Link href={`/brand-monitor?brandId=${brandId || ''}#files`} className="block group">
                        <Card className="h-full border border-slate-200 hover:border-orange-300 hover:shadow-xl hover:shadow-orange-100/50 transition-all duration-300 hover:-translate-y-1 bg-white">
                            <CardContent className="p-6 flex flex-col h-full">
                                <div className="w-12 h-12 bg-orange-50 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                                    <FileText className="h-6 w-6 text-orange-600" />
                                </div>
                                <h4 className="font-semibold text-slate-900 mb-2">Generate GEO Assets</h4>
                                <p className="text-sm text-slate-500 flex-1">
                                    Create optimized JSON-LD and Knowledge Graph files for AI engines.
                                </p>
                                <div className="mt-4 flex items-center text-orange-600 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity transform translate-x-[-10px] group-hover:translate-x-0">
                                    Create Files <ArrowRight className="ml-1 h-4 w-4" />
                                </div>
                            </CardContent>
                        </Card>
                    </Link>
                </div>
            </div>
        </div>
      </div>
    );
  }

  // Default Generator Mode
  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden">
      {/* Background Decorative Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-24 -left-24 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl" />
        <div className="absolute top-1/2 right-0 w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-3xl" />
      </div>

        {brandId ? (
            <div className="absolute top-4 left-4 sm:left-6 lg:left-8 z-50">
                <Link 
                href={`/brand-profiles/${brandId}`}
                className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 transition-all bg-white/80 backdrop-blur-md px-4 py-2 rounded-full border border-slate-200/60 hover:bg-white hover:border-slate-300 hover:shadow-md hover:-translate-y-0.5"
                >
                <ArrowLeft className="h-4 w-4" />
                Back to Profile
                </Link>
            </div>
        ) : (
            <div className="absolute top-4 left-4 sm:left-6 lg:left-8 z-50">
                <button 
                onClick={() => router.back()}
                className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 transition-all bg-white/80 backdrop-blur-md px-4 py-2 rounded-full border border-slate-200/60 hover:bg-white hover:border-slate-300 hover:shadow-md hover:-translate-y-0.5"
                >
                <ArrowLeft className="h-4 w-4" />
                Back
                </button>
            </div>
        )}

      <div className="relative z-10 container mx-auto py-12 px-4 max-w-4xl">
        {/* Back Button Removed from here */}
        
        <div className="mb-12 text-center space-y-4 mt-8">
           <div className="inline-flex items-center justify-center p-2 bg-white rounded-2xl shadow-sm border border-slate-100 mb-4">
              <div className="bg-gradient-to-br from-blue-500 to-purple-600 text-white p-2 rounded-xl">
                 <Sparkles className="h-6 w-6" />
              </div>
           </div>
           <h1 className="text-4xl md:text-5xl font-bold text-slate-900 tracking-tight">
             AEO Intelligence
           </h1>
           <p className="text-lg text-slate-600 max-w-2xl mx-auto">
             Generate professional AEO Intelligence reports. Analyze how well your website's data is structured for Large Language Models (LLMs) and optimized for AI discovery.
           </p>
        </div>

        {isFetchingReport && !generationSuccess ? (
             <div className="flex flex-col items-center justify-center py-20 space-y-6 bg-white/50 backdrop-blur-sm rounded-2xl border border-slate-100/50">
                <div className="relative">
                   <div className="absolute inset-0 bg-blue-100 rounded-full animate-ping opacity-50"></div>
                   <Loader2 className="h-12 w-12 animate-spin text-blue-600 relative z-10" />
                </div>
                <div className="text-center space-y-2">
                  <h2 className="text-xl font-semibold text-slate-900">Retrieving Report</h2>
                  <p className="text-slate-500">Fetching analysis data...</p>
                </div>
             </div>
        ) : (isGenerating || generationSuccess) ? (
          <Card className="border-none shadow-2xl bg-white/80 backdrop-blur-sm overflow-hidden relative">
             {/* Removed absolute back button from here as it is now global above */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-slate-100">
               <div className="h-full bg-gradient-to-r from-blue-500 to-purple-600 animate-indeterminate-bar" />
            </div>
            <CardContent className="p-12 flex flex-col items-center justify-center min-h-[400px] space-y-8">
               <div className="relative">
                 <div className="absolute inset-0 bg-blue-500/20 rounded-full animate-ping" />
                 <div className="relative bg-white p-4 rounded-full shadow-lg border border-slate-100">
                    <Loader2 className="h-10 w-10 animate-spin text-blue-600" />
                 </div>
               </div>
               
               <div className="space-y-6 w-full max-w-md">
                  <h2 className="text-2xl font-semibold text-center text-slate-900">
                    {generationSuccess ? "Analyzing Brand Data" : "Initializing Engine"}
                  </h2>
                  
                  <div className="space-y-3">
                    {loadingSteps.map((step, idx) => (
                      <div 
                        key={idx}
                        className={`flex items-center gap-4 p-3 rounded-lg transition-all duration-500 ${
                          idx === loadingStep 
                            ? 'bg-blue-50 border border-blue-100 opacity-100 translate-x-0' 
                            : 'opacity-40 scale-95'
                        }`}
                      >
                        <div className={`p-2 rounded-full ${idx === loadingStep ? 'bg-blue-100 text-blue-600' : 'bg-slate-100 text-slate-400'}`}>
                           <step.icon className="h-4 w-4" />
                        </div>
                        <span className={`text-sm font-medium ${idx === loadingStep ? 'text-blue-900' : 'text-slate-500'}`}>
                          {step.text}
                        </span>
                        {idx === loadingStep && (
                          <div className="ml-auto">
                            <span className="flex h-2 w-2 relative">
                              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
                            </span>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
               </div>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-8">
             <Card className="border-none shadow-xl bg-white overflow-hidden">
                <CardContent className="p-12 flex flex-col items-center justify-center text-center space-y-6">
                   {customerName && url ? (
                     <>
                       <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mb-2">
                          <Sparkles className="w-8 h-8 text-blue-600" />
                       </div>
                       <div className="space-y-2">
                          <h3 className="text-2xl font-bold text-slate-900">Ready to Analyze {customerName}</h3>
                          <p className="text-slate-500 max-w-md mx-auto text-base">
                            We're ready to perform a comprehensive AEO audit for <span className="font-medium text-slate-700">{url}</span>. This includes analyzing your data structure for LLMs. This process usually takes about 2 minutes.
                          </p>
                       </div>
                       <Button 
                         onClick={() => generateReport()}
                         className="bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-200 rounded-xl px-8 py-6 text-lg font-semibold transition-all hover:scale-105"
                       >
                         <Sparkles className="mr-2 h-5 w-5" />
                         Start AEO Audit
                       </Button>
                     </>
                   ) : (
                     <>
                       <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center">
                          <LayoutDashboard className="w-8 h-8 text-blue-600" />
                       </div>
                       <div className="space-y-2">
                          <h3 className="text-xl font-semibold text-slate-900">Start from Brand Profile</h3>
                          <p className="text-slate-500 max-w-sm mx-auto">
                            To generate an AEO Report, please select a brand from your dashboard and click "AEO Audit".
                          </p>
                       </div>
                       <Link href="/brand-profiles">
                         <Button className="bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-200 rounded-xl">
                           Go to Brand Profiles
                         </Button>
                       </Link>
                     </>
                   )}
                </CardContent>
             </Card>

             {/* Features Grid */}
             <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {[
                  {
                    title: "LLM Readiness",
                    desc: "Analyze how machine-readable your content is for major AI platforms.",
                    icon: BarChart3,
                    color: "text-blue-600",
                    bg: "bg-blue-50"
                  },
                  {
                    title: "Technical Schema",
                    desc: "Deep dive into your structured data to ensure AI readability.",
                    icon: Code,
                    color: "text-purple-600",
                    bg: "bg-purple-50"
                  },
                  {
                    title: "Actionable Strategy",
                    desc: "Get a prioritized list of optimizations to improve your standing.",
                    icon: CheckCircle,
                    color: "text-emerald-600",
                    bg: "bg-emerald-50"
                  }
                ].map((feature, i) => (
                  <div key={i} className="bg-white p-6 rounded-xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
                     <div className={`w-12 h-12 ${feature.bg} rounded-lg flex items-center justify-center mb-4`}>
                        <feature.icon className={`h-6 w-6 ${feature.color}`} />
                     </div>
                     <h3 className="font-semibold text-slate-900 mb-2">{feature.title}</h3>
                     <p className="text-sm text-slate-500 leading-relaxed">{feature.desc}</p>
                  </div>
                ))}
             </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function AEOReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="flex flex-col items-center space-y-4">
          <div className="relative">
             <div className="absolute inset-0 bg-blue-100 rounded-full animate-ping opacity-50"></div>
             <Loader2 className="h-12 w-12 animate-spin text-blue-600 relative z-10" />
          </div>
          <p className="text-lg text-slate-600 font-medium animate-pulse">Loading Experience...</p>
        </div>
      </div>
    }>
      <AEOReportContent />
    </Suspense>
  );
}