import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { htmlContent, customerName } = await request.json();

    if (!htmlContent || !customerName) {
      return NextResponse.json(
        { error: 'HTML content and customer name are required' },
        { status: 400 }
      );
    }

    // For now, we'll use the browser's print functionality
    // In a production environment, you might want to use puppeteer or similar
    const enhancedHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AEO Report - ${customerName}</title>
        <style>
          @media print {
            body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
            .no-print { display: none !important; }
            .page-break { page-break-before: always; }
            table { page-break-inside: avoid; }
            .card { page-break-inside: avoid; margin-bottom: 20px; }
            img { max-width: 100%; height: auto; }
          }
          @media screen {
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 20px; }
          }
          .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #004d99; padding-bottom: 20px; }
          .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
          .metric { background: #f7f7f7; padding: 10px; border-radius: 6px; margin: 10px 0; }
          .card { background: #fff; border: 1px solid #e4e4e4; padding: 12px; margin: 12px 0; border-radius: 6px; }
          table { width: 100%; border-collapse: collapse; margin: 10px 0; }
          th, td { padding: 8px; border: 1px solid #ddd; text-align: left; }
          th { background-color: #f5f5f5; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>AEO Report</h1>
          <p>Customer: ${customerName} | Generated: ${new Date().toLocaleString()}</p>
        </div>
        ${htmlContent}
        <div class="footer">
          <p>Generated by Firegeo AEO Analysis System</p>
        </div>
      </body>
      </html>
    `;

    return new NextResponse(enhancedHtml, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="aeo-report-${customerName}-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { 
        error: 'Failed to generate PDF',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}